# Generated by Django 5.2.4 on 2025-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='massage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
